package practica3;

/* @author CristianOmarJar */

public class Ventana extends javax.swing.JFrame {
    private Figura f =new Figura();    
    int tipodefigura = 0, transformacion = 0,relleno = 0;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);        
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rcirculo = new javax.swing.JRadioButton();
        rcuadrado = new javax.swing.JRadioButton();
        rtriangulo = new javax.swing.JRadioButton();
        rotrafigura = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        rsolido = new javax.swing.JRadioButton();
        rdegradado = new javax.swing.JRadioButton();
        rtextura = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        rgruesa = new javax.swing.JRadioButton();
        rdelgada = new javax.swing.JRadioButton();
        rpunteada = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        rrotacion = new javax.swing.JRadioButton();
        rescalacion = new javax.swing.JRadioButton();
        rtraslacion = new javax.swing.JRadioButton();
        Jfigura = new javax.swing.JLabel();
        Jrelleno = new javax.swing.JLabel();
        Jlinea = new javax.swing.JLabel();
        Jtranformacion = new javax.swing.JLabel();
        btndraw = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        pizarron = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rcirculo);
        rcirculo.setSelected(true);
        rcirculo.setText("Circulo");
        rcirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcirculoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rcuadrado);
        rcuadrado.setText("Cuadrado");

        buttonGroup1.add(rtriangulo);
        rtriangulo.setText("Triángulo");

        buttonGroup1.add(rotrafigura);
        rotrafigura.setText("Otra figura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rcirculo)
                    .addComponent(rcuadrado)
                    .addComponent(rtriangulo)
                    .addComponent(rotrafigura))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rcirculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rcuadrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rtriangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotrafigura)
                .addContainerGap())
        );

        buttonGroup2.add(rsolido);
        rsolido.setText("Solido");

        buttonGroup2.add(rdegradado);
        rdegradado.setText("Degradado");

        buttonGroup2.add(rtextura);
        rtextura.setText("Texturizado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rsolido)
                    .addComponent(rdegradado)
                    .addComponent(rtextura)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rsolido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdegradado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtextura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup3.add(rgruesa);
        rgruesa.setSelected(true);
        rgruesa.setText("Gruesa");

        buttonGroup3.add(rdelgada);
        rdelgada.setText("Delgada");

        buttonGroup3.add(rpunteada);
        rpunteada.setText("Punteada");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rgruesa)
                    .addComponent(rdelgada)
                    .addComponent(rpunteada)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rgruesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdelgada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rpunteada))
        );

        buttonGroup4.add(rrotacion);
        rrotacion.setText("Rotación");

        buttonGroup4.add(rescalacion);
        rescalacion.setText("Escalación");

        buttonGroup4.add(rtraslacion);
        rtraslacion.setText("Traslación");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rrotacion)
                    .addComponent(rescalacion)
                    .addComponent(rtraslacion)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rrotacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rescalacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtraslacion))
        );

        Jfigura.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Jfigura.setText("Figura");

        Jrelleno.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Jrelleno.setText("Relleno");

        Jlinea.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Jlinea.setText("Lineas");

        Jtranformacion.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Jtranformacion.setText("Transformación");

        btndraw.setText("Draw");
        btndraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndrawActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pizarronLayout = new javax.swing.GroupLayout(pizarron);
        pizarron.setLayout(pizarronLayout);
        pizarronLayout.setHorizontalGroup(
            pizarronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pizarronLayout.setVerticalGroup(
            pizarronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pizarron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jfigura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jrelleno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlinea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btndraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(Jtranformacion))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jfigura)
                    .addComponent(Jrelleno)
                    .addComponent(Jlinea)
                    .addComponent(Jtranformacion))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btndraw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pizarron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndrawActionPerformed
       
    if (rcuadrado.isSelected())
        tipodefigura = 1; 
    if (rcirculo.isSelected()) 
        tipodefigura = 2; 
    if (rtriangulo.isSelected()) 
        tipodefigura = 3;
    if (rotrafigura.isSelected()) 
        tipodefigura = 4;       
    if (rtraslacion.isSelected()) 
        transformacion = 1; 
    if (rrotacion.isSelected()) 
        transformacion = 2; 
    if (rescalacion.isSelected()) 
        transformacion = 3;        
    if (rdelgada.isSelected())
        dibujar(tipodefigura, 1, transformacion);
    if (rgruesa.isSelected())
        dibujar(tipodefigura, 2, transformacion);
    if (rpunteada.isSelected())
        dibujar(tipodefigura, 3, transformacion);
    }//GEN-LAST:event_btndrawActionPerformed
    public void dibujar(int tipodefigura, int linea, int transformacion){      

       if (rsolido.isSelected())relleno = 1;
       if (rtextura.isSelected())relleno = 2;
       if (rdegradado.isSelected())relleno = 3;
       
       f.Aplicar(pizarron.getGraphics(), 5, 130, 50, 50, relleno, tipodefigura, linea, transformacion);
    }

    private void rcirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcirculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcirculoActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        pizarron.repaint();
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jfigura;
    private javax.swing.JLabel Jlinea;
    private javax.swing.JLabel Jrelleno;
    private javax.swing.JLabel Jtranformacion;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndraw;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel pizarron;
    private javax.swing.JRadioButton rcirculo;
    private javax.swing.JRadioButton rcuadrado;
    private javax.swing.JRadioButton rdegradado;
    private javax.swing.JRadioButton rdelgada;
    private javax.swing.JRadioButton rescalacion;
    private javax.swing.JRadioButton rgruesa;
    private javax.swing.JRadioButton rotrafigura;
    private javax.swing.JRadioButton rpunteada;
    private javax.swing.JRadioButton rrotacion;
    private javax.swing.JRadioButton rsolido;
    private javax.swing.JRadioButton rtextura;
    private javax.swing.JRadioButton rtraslacion;
    private javax.swing.JRadioButton rtriangulo;
    // End of variables declaration//GEN-END:variables
}